import { VideoItem, UserStats } from './types';

export const INITIAL_VIDEOS: VideoItem[] = [
  {
    id: "v1",
    creator: "带你看苏州",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCcAhE4Jb_sB28XJCoi3p-EsBFtsUDsz0hmXu-ddUMi-8UXdvMADBZ96cR1-ioeHFFA2y-LQdqHegLjF9_bwdxD0h4w2zeS-p-dOvROCpKx2yVRLnOjjln0oSHC-Ci_GGBxvCIhlsn-yPL6yewyqTCJfvdLyMIchIxrwQHvYz2jpPqagQA8MV1ol-5aISJnDvpA29FLTdAQN4-I-E7qWcql6XUJx7nj7uj4bmCH5P0-MWNeAejems8rCd88oNQrKniT8WPDZIICA9MB",
    title: "苏州小桥流水与园林的慢生活",
    description: "苏州园林的慢生活，不仅是视觉的享受，更是心灵的修行。在这里学习雅思口语，仿佛穿越时空与古人对话。#苏州 #文化 #雅思口语 #日常英语",
    pills: ["雅思7分+词汇", "适用于口语第二部分", "文化主题"],
    bandScore: "雅思 8.0分",
    bgImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDVHSEB2bvap77uS-Esri1-WgsJOB3RtzvfiSibuX60KIG6fPklo8yngUn6Do2nLO9-R6FZ-HhF4QX5H2tIStqVsyU9CWzDR_5D_umXb8yxU33PGYGq5EuLP7jee2ngPjF9Vr0FUZmASC8pNpfqGL6bBsPKMfuX6QHP19LBy7O3PnEUGM24GlX4sw8Esp3qKCQUCL_f-dDgwQ-21no_cV5wC3RWo3bmKF7l0s0EHoqFv-HEIp34VTtGyqHLzCYYBPj_6FTKZF33WXZB",
    likes: 12400,
    comments: 856,
    bookmarks: 2100,
    shares: 420,
    hasLiked: false,
    hasBookmarked: false,
    englishTranscript: "The slow life in Suzhou gardens is a visual feast, but more importantly, a spiritual cultivation. Immersing oneself in such history feels like having a conversation with ancient scholars over space and time.",
    chineseTranscript: "苏州园林的慢生活不仅是视觉盛宴，更是一种心灵修行。在这个充满历史气息的园林中，让人感觉仿若穿越时空与古人隔空对话。",
    category: "Culture",
    keyVocab: [
      { word: "Classical Chinese Garden", pinyin: "gǔ diǎn yuán lín", translation: "古典园林" },
      { word: "Sense of slow living", pinyin: "màn shēng huó gǎn", translation: "慢生活感" },
      { word: "Spiritual cultivation", pinyin: "xīn líng xiū xíng", translation: "心灵修行" },
      { word: "Visual feast", pinyin: "shì jué shèng yàn", translation: "视觉盛宴" }
    ],
    speakingTemplate: "This place gives people a sense of peace that is hard to find in the bustling city. Visiting such a classical Chinese garden allows one to embrace the concept of slow living and admire traditional architectures.",
    usage: ["口语第二部分：描述一个你访问过的、令人难忘的地方。", "口语第三部分：旅游、全球化与社区价值探讨。"],
    duration: "0:45",
    ago: "2天前"
  },
  {
    id: "v2",
    creator: "科技探索者",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120",
    title: "人工智能驱动的社会伦理之思",
    description: "人工智能伦理正面临着重重考验，高新科技如何服务于全人类的同时不越界？这是我们在讨论雅思科技话题时的核心！ #科技 #人工智慧 #AI伦理 #科技雅思",
    pills: ["AI道德伦理", "复杂推理结构", "高科技主题"],
    bandScore: "雅思 7.5分",
    bgImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBJf1ikBaS_eIqpnk5mdKxNNPS2gvV_OLul7cWGfTlltQVzi-1LRSRpU9poVpJL24lYDCFnIcZIsnZTySHO_XYeFtf3NAmmfz47Q2U8Kst9Sy0s4xp6LUNAWp16w4V85alYQJ_jc_V3GL3AFj3rKYMA8zRJ3_e-6ZESXJdTxmjRdAQaE6ngGmfYrROSPnRVTVdKYKj8hrSRgWDTYOCuq6enlWT4LF3QLoB690iMC_RKjpw8oMcuko08j9MRI6gRj5rL29LRo8IfPFxJ",
    likes: 8600,
    comments: 512,
    bookmarks: 1400,
    shares: 198,
    hasLiked: false,
    hasBookmarked: false,
    englishTranscript: "Artificial intelligence is expanding rapidly, bringing forth key ethical debates on privacy parameters, bias mitigation, and human accountability. Navigating these constraints is essential for tech advancement.",
    chineseTranscript: "人工智能正在飞速扩张，引发了关于隐私参数、减少偏见以及人类问责制等关键伦理讨论。理清 these 约束对于推动技术进步至关重要。",
    category: "Tech",
    keyVocab: [
      { word: "Algorithmic bias", pinyin: "suàn fǎ piān jiàn", translation: "算法偏见" },
      { word: "Privacy parameters", pinyin: "yǐn sī cān shù", translation: "隐私参数" },
      { word: "Human accountability", pinyin: "rén lèi wèn zé", translation: "人类问责机制" },
      { word: "Ethical parameters", pinyin: "lún lǐ dù liáng", translation: "伦理准则" }
    ],
    speakingTemplate: "While artificial intelligence offers massive breakthroughs in society, we must outline robust privacy parameters and solve algorithmic bias to support human accountability.",
    usage: ["口语第三部分：科技与人类文明进步探讨。", "口语第三部分：批判性讨论关于未来自动化工作的预测。"],
    duration: "1:20",
    ago: "5小时前"
  },
  {
    id: "v3",
    creator: "古建雅思行",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=120",
    title: "现代都市中传统建筑之魂",
    description: "在钢筋水泥的现代都市中，古典庙宇和雕梁画栋依然保留着城市的灵魂，是承载历史厚重感的实体。 #中国风建筑 #传统文化 #雅思备考",
    pills: ["文化遗产保护", "雅思8分词汇", "城市文化"],
    bandScore: "雅思 8.0分",
    bgImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCOb_23R6Z-2yl3bd-wbvO-kSnHcGAoF8iQXzOnlsft-ukQa4pLcAto9GJibEvhKhaZTzD0HVqdW4BjjvVKz5HR8OFgmxPmJ0ZvV4oGLeq9Ub-TexMEAzB7RguPSfR3nZb9ojks_-6e2Bz-a4GpTWyhIUkWK3qAHTAGK73g7paZZAKnceYhQVC1yX4zmRNOWvLyY_dtbSvROn87t2t2F3zZs-8i83vlL9TfD4Go0CzrGQIQ4wKcNqXl0RXIQDMh7_KZT2aCaiyTaHIr",
    likes: 15400,
    comments: 1105,
    bookmarks: 3200,
    shares: 890,
    hasLiked: false,
    hasBookmarked: false,
    englishTranscript: "The preservation of traditional landmarks like historic temples in metropolitan areas offers a tangible bridge between ancestral wisdom and high-velocity urban developments.",
    chineseTranscript: "在大都市中保留历史寺庙等传统地标，为祖辈智慧与高速运转的城市发展之间搭建起一座有形的桥梁。",
    category: "Culture",
    keyVocab: [
      { word: "Concrete jungle", pinyin: "hùn níng tǔ sēn lín", translation: "钢筋水泥森林" },
      { word: "Tangible heritage", pinyin: "yǒu xíng yí chǎn", translation: "有形文化遗产" },
      { word: "Ancestral legacy", pinyin: "zǔ bèi yí chǎn", translation: "祖辈留下的遗产" },
      { word: "Metropolitan preserve", pinyin: "dū shì bǎo hù qū", translation: "大都市风貌保护" }
    ],
    speakingTemplate: "Amidst the rapidly expanding concrete jungle of contemporary cities, preserving traditional temples operates as a tangible heritage that connects us with our ancestral legacy.",
    usage: ["口语第二部分：描述你们国家的一座历史古建筑。", "口语第三部分：在不断扩张的大都市中如何保持历史特色。"],
    duration: "0:45",
    ago: "2天前"
  },
  {
    id: "v4",
    creator: "园林雅思居",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=120",
    title: "古塔下的宁静避风港",
    description: "黄昏时刻的园林古塔，伴随着幽幽晚钟和清幽池塘，绝对是每一个旅游者寻找宁静的最佳去处。 #园林古建 #小众旅行 #英文日常",
    pills: ["沉浸式旅行体验", "幽静之美", "风景名胜区"],
    bandScore: "雅思 7.0分",
    bgImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBZMpM4570Ge0r4qI7o0XnHkh7fMsL_sIcaDXt05rWSwTTXnh_o_-s0batSImgwLFHo3obYHxSzi2AzXtGBrCxRdCfPQci8rcE1McZ8k4qiq_xLMk5uElGJ8ZgUS81wLa1LsPpurueu20WjpW2ooiJ-d6U9E0zIjKcL7QCpYUswhyOeMXVyiXfhgZzjQuRO3W4yywj1SDBoiczZxEyyRVr9yWKW-mM4g0TPlgkLIgiOMGfuifSZGUoTcpDJIbTI8eSP-UoTnheEqDpg",
    likes: 6730,
    comments: 312,
    bookmarks: 840,
    shares: 112,
    hasLiked: false,
    hasBookmarked: false,
    englishTranscript: "During early twilight, classical garden pagodas casting long shadows upon still scenic koi ponds present a breathtaking perspective for spiritual replenishment.",
    chineseTranscript: "在傍晚时刻，倒映在清幽锦鲤池里的古典园林宝塔，为寻找心灵港湾提供了绝美的图景。",
    category: "Travel",
    keyVocab: [
      { word: "Spiritual replenishment", pinyin: "shén líng bǔ jǐ", translation: "精神补充/心灵洗礼" },
      { word: "Tranquil scenery", pinyin: "yōu jìng fēng guāng", translation: "清幽宁静风光" },
      { word: "Shadowy pagoda", pinyin: "gǔ tǎ shēn yǐng", translation: "古塔巍巍叠影" },
      { word: "Scenic koi ponds", pinyin: "jǐn lǐ chí táng", translation: "锦鲤池塘" }
    ],
    speakingTemplate: "Exploring classical attractions lets tourists appreciate the tranquil scenery of shadowy pagodas reflecting in scenic koi ponds, achieving deep spiritual replenishment.",
    usage: ["口语第二部分：描述一次完美旅行或大自然美景。", "口语第三部分：旅行心理学与精神状态的修复作用。"],
    duration: "1:15",
    ago: "1周前"
  },
  {
    id: "v5",
    creator: "温情雅思说",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=120",
    title: "现代家庭的代际关系大撞击",
    description: "两代人之间的思想碰撞——从传统的孝道、家庭陪伴到现代社会的独立观念，如何用高级词汇分析雅思家庭类话题？ #雅思口语 #家庭成长 #大作文热点",
    pills: ["家庭核心主题", "第三部分深度探讨", "雅思高分重点词汇"],
    bandScore: "雅思 8.5分",
    bgImage: "https://images.unsplash.com/photo-1609234656388-0ff363383899?auto=format&fit=crop&q=80&w=600",
    likes: 9320,
    comments: 724,
    bookmarks: 1850,
    shares: 341,
    hasLiked: false,
    hasBookmarked: false,
    englishTranscript: "Modern intergenerational relationships represent a shift from unquestioned filial piety towards collaborative autonomy, where distinct age cohorts seek mutual validation.",
    chineseTranscript: "现代代际关系展现出从无条件孝顺到协同自主的转变，各年龄段群体在此之中寻求对彼此价值的认可。",
    category: "Family",
    keyVocab: [
      { word: "Filial piety", pinyin: "xiào dào", translation: "孝顺/传统孝心" },
      { word: "Intergenerational shift", pinyin: "dài jì zhuǎn biàn", translation: "代际关系移易" },
      { word: "Collaborative autonomy", pinyin: "xié tóng zì zhǔ", translation: "协同自治权" },
      { word: "Mutual validation", pinyin: "hù xiāng rèn kě", translation: "相互认可" }
    ],
    speakingTemplate: "In contemporary society, we see a notable intergenerational shift where children maintain standard filial piety while establishing collaborative autonomy founded on mutual validation.",
    usage: ["口语第三部分：探讨核心家庭与大家庭之间的层级关系。", "口语第三部分：分析当今社会对老年人关怀的代际转变。"],
    duration: "2:10",
    ago: "3天前"
  }
];

export const INITIAL_USER_STATS: UserStats = {
  targetScore: 7.5,
  currentEstimatedScore: 7.2,
  pronunciation: 75,
  vocabulary: 80,
  grammar: 70,
  fluency: 74,
  totalRemixes: 12,
  completedTasks: 8
};
